version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Gradle...
      - curl -sL https://services.gradle.org/distributions/gradle-8.14-bin.zip -o gradle.zip
      - unzip -q gradle.zip
      - export PATH=$PATH:$PWD/gradle-8.14/bin
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew shadowJar
  post_build:
    commands:
      - echo Build completed on `date`
      - mv build/libs/todolist-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - todolist-0.0.1-SNAPSHOT.jar
  discard-paths: yes